#!/bin/bash

# --------------------------------------------------------------------------- #
#                               Website Builder                               #
#                         par Alexandre SBEGHEN, 2026                         #
# --------------------------------------------------------------------------- #

# 
# --------------- Constantes ------------------------------------------------ #
# 

readonly APP_NAME="$0"
readonly APP_VERSION="1.0.0-SNAPSHOT" # Version du projet
readonly SASS_COMMAND="sass" # Commande pour exécuter Sass

readonly OPTION_SASS_COMPILE="--sass-compile" # Compiler les fichier Sass (.scss)
readonly OPTION_SASS_COMPRESS="--sass-compress" # Minifier les Sass compilés
readonly OPTION_SASS_NO_SOURCE_MAP="--sass-no-source-map" # Ne pas créer les source map de Sass
readonly OPTION_CSS_MINIFY="--css-minify" # Minifier les styles CSS
readonly OPTION_JS_MINIFY="--js-minify" # Minifier les scripts JS

readonly BYPASS_INDEX_VERIFICATION=0 # Ignorer la vérification de l'index
readonly BYPASS_SASS_VERIFICATION=0 # Ignorer l'existence de Sass

readonly BUILD_IGNORE=("$APP_NAME" "build" "README.md" "LICENSE" "*.sass") # Ignorer certains fichiers lors du build (Peut être agrandi)

# 
# --------------- Fonctions d'affichage ------------------------------------- #
# 

# Afficher le header de l'application
# i.e : Nom, auteur, version, etc
print_app_header() {
    echo "Website Builder, Alexandre SBEGHEN, 2026"
    echo "Version $APP_VERSION"
    echo "GitHub: https://github.com/Alexandre-SBEGHEN"
    echo "Repo: https://github.com/Alexandre-SBEGHEN/Website-Builder"
}

# Afficher le guide d'utilisation de l'application
print_app_usage() {
    echo "Usage: ${APP_NAME} [<options>...] [<index_directory>]"
    echo
    echo "<Options>"
    printf "  %-20s : %s" "$OPTION_SASS_COMPILE"        "Compile your sass to CSS (requires Dart Sass)"; echo
    printf "  %-20s : %s" "$OPTION_SASS_COMPRESS"       "Minify the compiled Sass"; echo
    printf "  %-20s : %s" "$OPTION_SASS_NO_SOURCE_MAP"  "Prevent Sass from creating source maps"; echo
    printf "  %-20s : %s" "$OPTION_CSS_MINIFY"          "Minify your CSS"; echo
    printf "  %-20s : %s" "$OPTION_JS_MINIFY"           "Minify your JavaScript"; echo
}

# Affiche le header d'un message d'erreur
print_error_header() {
    echo "Command line error"
}

# Affiche une ERREUR
# -> le dernier argument n'est PAS un répertoire
print_error_last_arg_not_repertory() {
    echo "Last argument must be the index directory"
}

# Affiche une ERREUR
# -> index du site (php/html) non trouvé
print_error_index_not_found() {
    echo "HTML or PHP index not found at '${1}'"
}

# Affiche une ERREUR
# -> Sass n'est pas installé
print_error_sass_not_found() {
    echo "Sass could not be found"
}

# Affiche une ERREUR
# -> Option inconnue
print_error_unknown_command() {
    echo "Unknown command: ${1}"
}

# Affiche une INFO
# -> Le build a été effectué avec succès
print_info_build_success() {
    echo "Website compiled successfully to '${1}'"
}

#
# --------------- Programme principal --------------------------------------- #
#

# Arguments
argc=$#
argv=("$@")

# Afficher le header
echo
print_app_header
echo

# Afficher le guide d'utilisation (si 0 argument)
if (( argc == 0 )); then
    print_app_usage
    echo
    exit 0
fi

# ---------- Vérification de l'index ----------
last_arg="${argv[@]: -1}"
if (( $BYPASS_INDEX_VERIFICATION == 0 )); then
    # Le dernier argument est-il un répertoire ?
    if [[ ! -d "$last_arg" ]]; then
        print_error_header
        print_error_last_arg_not_repertory
        echo
        exit 1
    fi
    # Un index existe-t-il dans le répertoire ?
    if [[ ! -f "${last_arg}/index.html" && ! -f "${last_arg}/index.php" ]]; then
        print_error_header
        print_error_index_not_found "$last_arg"
        echo
        exit 1
    fi
fi
website_directory="$last_arg"

# ---------- Options ----------
option_sass_compile=0
option_sass_compress=0
option_sass_no_source_map=0
option_css_minify=0
option_js_minify=0

for option in "${argv[@]:0:$((argc-1))}"; do # Tous les arguments SAUF le dernier
    if [[ "$option" = "$OPTION_SASS_COMPILE" ]]; then
        option_sass_compile=1
        continue
    elif [[ "$option" = "$OPTION_SASS_COMPRESS" ]]; then
        option_sass_compress=1
        continue
    elif [[ "$option" = "$OPTION_SASS_NO_SOURCE_MAP" ]]; then
        option_sass_no_source_map=1
        continue
    elif [[ "$option" = "$OPTION_CSS_MINIFY" ]]; then
        option_css_minify=1
        continue
    elif [[ "$option" = "$OPTION_JS_MINIFY" ]]; then
        option_js_minify=1
        continue
    fi
        
    # Commande inconnue
    print_error_header
    print_error_unknown_command "$option"
    echo
    exit 1
done

# ---------- Vérification de Sass (si actif) ----------
if (( $option_sass_compile == 1 && $BYPASS_SASS_VERIFICATION == 0 )) \
    && ! command -v "$SASS_COMMAND" >/dev/null 2>&1; then

    print_error_header
    print_error_sass_not_found
    echo
    exit 1
fi

# ---------- Vidage / Création du dossier build ----------
build_directory="${website_directory}/build"
[[ -d "$build_directory" ]] && $(echo rm -rf "${build_directory}"/*) || $(mkdir "$build_directory")

# ---------- Copie des fichiers ----------
for f in "${website_directory}"/*; do
    fname=$(basename "$f")

    # Ne pas copier s'il est dans BUILD_IGNORE
    skip=0
    for ignore in "${BUILD_IGNORE[@]}"; do
        if [[ "$fname" = "$ignore" ]]; then
            skip=1
            break
        fi
    done
    (( skip == 1 )) && continue

    # Copier
    cp -r "$f" "$build_directory"/
done

# ---------- Sass, CSS, JS ----------
for f in $(find "$build_directory"/*); do
    # Ignorer si ce n'est pas un fichier
    if [[ ! -f "$f" ]]; then
        continue
    fi

    extension="${f##*.}"

    # Minifier les CSS / JS (=> retirer espaces/sauts de lignes + commentaires)
    if [[ ($option_js_minify -eq 1 && "$extension" = "js") || ($option_css_minify -eq 1 && "$extension" = "css") ]]; then
        # Commentaires
        content=$(cat "$f")
        len="${#content}"

        state="CODE"
        output=""
        # Algorithme de suppression des commentaires
        # (pseudo-code issu de Claude, traduit en bash par moi)
        for (( i=0; i<$len; ++i )); do
            c="${content:$i:1}"
            next="${content:((i+1)):1}"
            (( i == len-1 )) && next="EOF"

            if [[ "$state" = "CODE" ]]; then
                if [[ "$c" = "\"" || "$c" = "'" || "$c" = "\`" ]]; then
                    state="STRING"
                    delimiter="$c"
                    output+="$c"
                elif [[ "$c" = "/" && "$next" = "/" ]]; then
                    state="COMMENT_LINE"
                    ((i+=1))
                elif [[ "$c" = "/" && "$next" = "*" ]]; then
                    state="COMMENT_BLOCK"
                    ((i+=1))
                elif [[ "$c" = " " && "$next" = " " ]]; then
                    ((i+=1))
                else
                    output+="$c"
                fi
            elif [[ "$state" = "STRING" ]]; then
                output+="$c"
                if [[ "$c" = $'\\' ]]; then
                    output+="$next"
                    ((i+=1))
                elif [[ "$c" = "$delimiter" ]]; then
                    state="CODE"
                fi
            elif [[ "$state" = "COMMENT_LINE" ]]; then
                if [[ "$c" = $'\n' ]]; then
                    state="CODE"
                    output+="$c"
                fi
            elif [[ "$state" = "COMMENT_BLOCK" ]]; then
                if [[ "$c" = "*" && "$next" = "/" ]]; then
                    state="CODE"
                    ((i+=1))
                fi
            fi

            # output+="$c"
        done

        # Enregistrer sans retours à la ligne
        echo "$output" | tr '\t' ' ' | tr -d '\r\n' > "$f"

        continue
    fi

    # Compiler les sass
    if [[ "$extension" = "scss" ]]; then
        (( $option_sass_compile )) && sass \
            $((( $option_sass_compress )) && echo "--style=compressed") \
            $((( $option_sass_no_source_map )) && echo "--no-source-map") \
            "${f}" "${f%%.*}.css"
        
        rm "$f"
    fi
done

# ---------- Succès ----------
print_info_build_success "$build_directory"
echo
